### ISSUE TITLE
10.11, Launchers not Created

### ISSUE THREAD

**Issue by ryness** [djbclark/chrome-schismator#1]
Running 10.11, when I run ~/chrome-apartheid.sh it creates folders in Application Support/Google/Chrome/cdi\* but doesn't properly make a launcher for each profile.
![chrome_and_ryans_ _-bash_ _172x65](https://cloud.githubusercontent.com/assets/13770089/10624119/fc411940-7741-11e5-9c6c-4443e7728c4c.jpg)

**Comment by wayferer** [comment]
I'm on 10.11.2 and I can't even get as far as you have. I get:

```
ls: Default/Preferences: No such file or directory
Be patient, this involves copying a lot of data...
Working on profile: -n Profile_1
ln: illegal option --  
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
```

Am running as sudo and with the correct user. This is my folder after running the command (the three folders are empty):

<img width="635" alt="screen shot 2016-01-25 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/1575559/12565545/840f411a-c37a-11e5-94c0-fbbd632a980b.png">

**Comment by djbclark** [comment]
I think this was just because newer chrome doesn't have "Default" folder be the first profile folder, but instead starts with "Profile 1". Modified script to only deal with Default folder if it exists. Thanks for the report, and please tell me if you still have problems! Great to see someone else using this :-)
